# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWcl6vD2CqYMyYXhdyuNCfq6gxzNmJGb
"""

!pip install pandas scikit-learn matplotlib openpyxl

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Load the Excel file (assuming the uploaded file is append.xlsx)
df = pd.read_excel('append.xlsx', sheet_name='append')
df.head()

from sklearn.preprocessing import LabelEncoder

df_clean = df.copy()
label_encoders = {}

for col in df_clean.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df_clean[col] = le.fit_transform(df_clean[col])
    label_encoders[col] = le

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

X = df_clean.drop('y', axis=1)
y = df_clean['y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

plt.figure(figsize=(20, 10))
plot_tree(clf,
          feature_names=X.columns,
          class_names=label_encoders['y'].classes_,
          filled=True,
          max_depth=3,
          fontsize=10)

plt.title("Decision Tree Classifier (Depth=3)")
plt.show()